spring.application.name=questoes

# Conexão com o PostgreSQL local
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/enadedb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:igoradmin}
spring.datasource.driver-class-name=org.postgresql.Driver

# Estratégia do Hibernate para banco real
# "update" apenas atualiza as tabelas ou cria se não existirem. NUNCA apaga seus dados!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Desativa o script automático para não reinserir dados duplicados toda vez
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false

# Permite que a paginação aceite parâmetros de tamanho de página de até 250 itens
spring.data.web.pageable.max-page-size=250